### ISSUE TITLE
[Help!] No such module "Snapkit"

### ISSUE THREAD

**Issue by functionsfund** [ShawnMa16/Tom_and_Jerry#4]
Hi Shawn,

After I install CocoaPods and Snapkit:

![screen shot 2018-11-18 at 4 29 04 pm](https://user-images.githubusercontent.com/33078987/48670247-8d473d00-eb4f-11e8-99e3-7096d18339ab.png)

I still have this error:

![screen shot 2018-11-18 at 4 29 34 pm](https://user-images.githubusercontent.com/33078987/48670248-96d0a500-eb4f-11e8-9361-42e519c42107.png)

**Comment by ShawnMa16** [comment]
Hi Allen,

Have you tried to open "Tom_Jerry.xcworkspace" instead of "Tom_Jerry.xcodeproj"?
As you now should work in Xcode workspace because of the pods

**Comment by functionsfund** [comment]
Thanks, Shawn @ShawnMa16 ! Problem solved :P sorry for this stupid question
